version: '3.3'
services:
    monitor:
        image: asboldyrev/monitor
        container_name: monitor
        restart: unless-stopped
        ports:
          - "8181:80"
        volumes:
          - ./json/:/usr/share/nginx/html/json/:ro
