version: '3.3'
services:
    monitor:
        image: asboldyrev/monitor
        container_name: monitor
        restart: unless-stopped
        pid: host
        privileged: true
        ports:
          - "8181:8181"
        volumes:
          - ./data.json:/app/storage/data.json
          - ./.env:/app/.env
          - ./config/monitor.php:/app/config/monitor.php
